# Generated by Django 2.2.1 on 2019-05-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producr_name',
            new_name='product_name',
        ),
    ]
