# Generated by Django 2.2.1 on 2019-05-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190516_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priec',
            new_name='price',
        ),
    ]
